"""
scripts/setup_embedded.py — 在目标机器上初始化内嵌环境

用法：
    .\vendor\python\python.exe scripts\setup_embedded.py

功能：
- 用 vendor/python 创建 .venv
- 从 vendor/wheels 安装依赖
- 设置离线模型/浏览器环境变量
- 初始化项目 git 仓库（供 git_commit 工具使用）
"""

from __future__ import annotations
import os
import subprocess
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _info(msg: str) -> None:
    print(f"[setup_embedded] {msg}")


def _error(msg: str) -> None:
    print(f"[setup_embedded] ERROR: {msg}", file=sys.stderr)


def _find_vendor_python() -> Path:
    candidate = _PROJECT_ROOT / "vendor" / "python" / "python.exe"
    if candidate.exists():
        return candidate
    # fallback to system python
    return Path(sys.executable)


def _find_vendor_node() -> Path:
    return _PROJECT_ROOT / "vendor" / "node" / "node.exe"


def _find_vendor_git() -> Path:
    return _PROJECT_ROOT / "vendor" / "git" / "cmd" / "git.exe"


def _create_venv(python_exe: Path) -> Path:
    venv_dir = _PROJECT_ROOT / ".venv"
    venv_python = venv_dir / "Scripts" / "python.exe"
    if venv_python.exists():
        _info("venv already exists")
        return venv_python
    _info("creating .venv from embedded Python...")
    subprocess.run([str(python_exe), "-m", "venv", str(venv_dir)], check=True)
    return venv_python


def _install_from_wheels(venv_python: Path) -> None:
    wheels_dir = _PROJECT_ROOT / "vendor" / "wheels"
    if not wheels_dir.exists() or not any(wheels_dir.glob("*.whl")):
        _error(f"no wheels found in {wheels_dir}; run scripts/build_embedded.py first")
        return
    _info("installing packages from vendor/wheels...")
    subprocess.run(
        [
            str(venv_python), "-m", "pip", "install",
            "--no-index", "--find-links", str(wheels_dir),
            "-r", str(_PROJECT_ROOT / "requirements.txt"),
        ],
        check=True,
    )


def _write_env_file() -> None:
    """生成 .env.embedded，记录离线资源路径。"""
    lines = [
        "# Auto-generated by scripts/setup_embedded.py",
        f"TTMEVOLVE_ROOT={_PROJECT_ROOT}",
        f"TTMEVOLVE_PORTABLE_ROOT={_PROJECT_ROOT / 'portable'}",
        f"TTMEVOLVE_HOME={_PROJECT_ROOT / 'portable' / 'home'}",
        f"TTMEVOLVE_CACHE={_PROJECT_ROOT / 'portable' / 'cache'}",
        f"TTMEVOLVE_TEMP={_PROJECT_ROOT / 'portable' / 'tmp'}",
        f"TAPTAP_MAKER_HOME={_PROJECT_ROOT / 'portable' / 'home' / '.taptap-maker'}",
        f"TTM_MAKER_HOME={_PROJECT_ROOT / 'portable' / 'home' / '.taptap-maker'}",
        f"HOME={_PROJECT_ROOT / 'portable' / 'home'}",
        f"USERPROFILE={_PROJECT_ROOT / 'portable' / 'home'}",
        f"APPDATA={_PROJECT_ROOT / 'portable' / 'home' / 'AppData' / 'Roaming'}",
        f"LOCALAPPDATA={_PROJECT_ROOT / 'portable' / 'home' / 'AppData' / 'Local'}",
        f"XDG_CACHE_HOME={_PROJECT_ROOT / 'portable' / 'cache' / 'xdg'}",
        f"PIP_CACHE_DIR={_PROJECT_ROOT / 'portable' / 'cache' / 'pip'}",
        f"npm_config_cache={_PROJECT_ROOT / 'portable' / 'cache' / 'npm'}",
        f"npm_config_prefix={_PROJECT_ROOT / 'portable' / 'node-global'}",
        f"HF_HOME={_PROJECT_ROOT / 'portable' / 'cache' / 'huggingface'}",
        f"HUGGINGFACE_HUB_CACHE={_PROJECT_ROOT / 'portable' / 'cache' / 'huggingface' / 'hub'}",
        f"TRANSFORMERS_CACHE={_PROJECT_ROOT / 'portable' / 'cache' / 'huggingface' / 'transformers'}",
        f"SENTENCE_TRANSFORMERS_HOME={_PROJECT_ROOT / 'vendor' / 'embeddings'}",
        f"TORCH_HOME={_PROJECT_ROOT / 'portable' / 'cache' / 'torch'}",
        f"MPLCONFIGDIR={_PROJECT_ROOT / 'portable' / 'cache' / 'matplotlib'}",
        f"PLAYWRIGHT_BROWSERS_PATH={_PROJECT_ROOT / 'vendor' / 'playwright'}",
        f"TMP={_PROJECT_ROOT / 'portable' / 'tmp'}",
        f"TEMP={_PROJECT_ROOT / 'portable' / 'tmp'}",
        f"TMPDIR={_PROJECT_ROOT / 'portable' / 'tmp'}",
    ]
    python_exe = _PROJECT_ROOT / "vendor" / "python" / "python.exe"
    node_exe = _PROJECT_ROOT / "vendor" / "node" / "node.exe"
    git_exe = _PROJECT_ROOT / "vendor" / "git" / "cmd" / "git.exe"
    if python_exe.exists():
        lines.append(f"TTM_PYTHON_EXE={python_exe}")
    if node_exe.exists():
        lines.append(f"TTM_NODE_EXE={node_exe}")
    if git_exe.exists():
        lines.append(f"TTM_GIT_EXE={git_exe}")
    (_PROJECT_ROOT / ".env.embedded").write_text("\n".join(lines) + "\n", encoding="utf-8")
    _info("wrote .env.embedded")


def _init_git_repo() -> None:
    git_dir = _PROJECT_ROOT / ".git"
    if git_dir.exists():
        return
    git_exe = _find_vendor_git()
    if not git_exe.exists():
        _info("embedded git not found, skipping git init")
        return
    _info("initializing git repository...")
    subprocess.run([str(git_exe), "init"], cwd=_PROJECT_ROOT, check=True)
    subprocess.run([str(git_exe), "config", "user.email", "ttmevolve@local"], cwd=_PROJECT_ROOT, check=True)
    subprocess.run([str(git_exe), "config", "user.name", "TTMEvolve"], cwd=_PROJECT_ROOT, check=True)


def main() -> None:
    python_exe = _find_vendor_python()
    _info(f"using Python: {python_exe}")

    venv_python = _create_venv(python_exe)
    _install_from_wheels(venv_python)
    _write_env_file()
    _init_git_repo()

    node_exe = _find_vendor_node()
    if node_exe.exists():
        _info(f"embedded Node available: {node_exe}")

    _info("setup complete")
    _info("run start-embedded.bat to launch")


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    main()
